In [1]:
import pandas as pd

In [2]:
# load the data with the states and counties and their fips
counties = pd.read_csv('https://raw.githubusercontent.com/kjhealy/fips-codes/master/county_fips_master.csv', encoding = 'latin-1')

In [3]:
counties.head()

,fips,county_name,state_abbr,state_name,long_name,sumlev,region,division,state,county,crosswalk,region_name,division_name
0,1001,Autauga County,AL,Alabama,Autauga County AL,50.0,3.0,6.0,1.0,1.0,3-6-1-1,South,East South Central
1,1003,Baldwin County,AL,Alabama,Baldwin County AL,50.0,3.0,6.0,1.0,3.0,3-6-1-3,South,East South Central
2,1005,Barbour County,AL,Alabama,Barbour County AL,50.0,3.0,6.0,1.0,5.0,3-6-1-5,South,East South Central
3,1007,Bibb County,AL,Alabama,Bibb County AL,50.0,3.0,6.0,1.0,7.0,3-6-1-7,South,East South Central
4,1009,Blount County,AL,Alabama,Blount County AL,50.0,3.0,6.0,1.0,9.0,3-6-1-9,South,East South Central

In [4]:
counties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3146 entries, 0 to 3145
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fips           3146 non-null   int64
 1   county_name    3146 non-null   object
 2   state_abbr     3146 non-null   object
 3   state_name     3146 non-null   object
 4   long_name      3146 non-null   object
 5   sumlev         3143 non-null   float64
 6   region         3143 non-null   float64
 7   division       3143 non-null   float64
 8   state          3143 non-null   float64
 9   county         3143 non-null   float64
 10  crosswalk      3146 non-null   object
 11  region_name    3143 non-null   object
 12  division_name  3143 non-null   object
dtypes: float64(5), int64(1), object(7)
memory usage: 319.6+ KB

In [5]:
counties.loc[counties['state_abbr'] == 'MN',].head()

,fips,county_name,state_abbr,state_name,long_name,sumlev,region,division,state,county,crosswalk,region_name,division_name
1316,27001,Aitkin County,MN,Minnesota,Aitkin County MN,50.0,2.0,4.0,27.0,1.0,2-4-27-1,Midwest,West North Central
1317,27003,Anoka County,MN,Minnesota,Anoka County MN,50.0,2.0,4.0,27.0,3.0,2-4-27-3,Midwest,West North Central
1318,27005,Becker County,MN,Minnesota,Becker County MN,50.0,2.0,4.0,27.0,5.0,2-4-27-5,Midwest,West North Central
1319,27007,Beltrami County,MN,Minnesota,Beltrami County MN,50.0,2.0,4.0,27.0,7.0,2-4-27-7,Midwest,West North Central
1320,27009,Benton County,MN,Minnesota,Benton County MN,50.0,2.0,4.0,27.0,9.0,2-4-27-9,Midwest,West North Central

In [6]:
# create fips code for the states
counties['county_fips'] = counties['fips'].astype(str).str.rjust(5, '0')

In [7]:
counties.head()

,fips,county_name,state_abbr,state_name,long_name,sumlev,region,division,state,county,crosswalk,region_name,division_name,county_fips
0,1001,Autauga County,AL,Alabama,Autauga County AL,50.0,3.0,6.0,1.0,1.0,3-6-1-1,South,East South Central,01001
1,1003,Baldwin County,AL,Alabama,Baldwin County AL,50.0,3.0,6.0,1.0,3.0,3-6-1-3,South,East South Central,01003
2,1005,Barbour County,AL,Alabama,Barbour County AL,50.0,3.0,6.0,1.0,5.0,3-6-1-5,South,East South Central,01005
3,1007,Bibb County,AL,Alabama,Bibb County AL,50.0,3.0,6.0,1.0,7.0,3-6-1-7,South,East South Central,01007
4,1009,Blount County,AL,Alabama,Blount County AL,50.0,3.0,6.0,1.0,9.0,3-6-1-9,South,East South Central,01009

In [8]:
# create the state fips for each state
counties['state_fips'] = counties['county_fips'].str[:2].str.ljust(5, '0')

In [9]:
counties.loc[counties['state_abbr'] == 'MN',].head()

,fips,county_name,state_abbr,state_name,long_name,sumlev,region,division,state,county,crosswalk,region_name,division_name,county_fips,state_fips
1316,27001,Aitkin County,MN,Minnesota,Aitkin County MN,50.0,2.0,4.0,27.0,1.0,2-4-27-1,Midwest,West North Central,27001,27000
1317,27003,Anoka County,MN,Minnesota,Anoka County MN,50.0,2.0,4.0,27.0,3.0,2-4-27-3,Midwest,West North Central,27003,27000
1318,27005,Becker County,MN,Minnesota,Becker County MN,50.0,2.0,4.0,27.0,5.0,2-4-27-5,Midwest,West North Central,27005,27000
1319,27007,Beltrami County,MN,Minnesota,Beltrami County MN,50.0,2.0,4.0,27.0,7.0,2-4-27-7,Midwest,West North Central,27007,27000
1320,27009,Benton County,MN,Minnesota,Benton County MN,50.0,2.0,4.0,27.0,9.0,2-4-27-9,Midwest,West North Central,27009,27000

In [10]:
# create a list of the variables I will keep
keep_list = ['state_name', 'state_fips', 'county_name', 'county_fips']
data = counties[keep_list]

In [11]:
data.head()

  state_name state_fips     county_name county_fips
0    Alabama      01000  Autauga County       01001
1    Alabama      01000  Baldwin County       01003
2    Alabama      01000  Barbour County       01005
3    Alabama      01000     Bibb County       01007
4    Alabama      01000   Blount County       01009

In [12]:
# create the start of the year quarter when each state changed their minimum wage
start = {}
start['Alabama'] = 'Never'
start['Alaska'] = 'Always'
start['Arizona'] = '2007-Q1'
start['Arkansas'] = '2006-Q4'
start['California'] = 'Always'
start['Colorado'] = '2007-Q1'
start['Connecticut'] = 'Always'
start['Delaware'] = '1999-Q2'
start['Florida'] = '2005-Q2'
start['Georgia'] = 'Never'
start['Hawaii'] = 'Always'
start['Idaho'] = 'Never'
start['Illinois'] = '2004-Q1'
start['Indiana'] = 'Never'
start['Iowa'] = '2007-Q2'
start['Kansas'] = 'Never'
start['Kentucky'] = 'Never'
start['Louisiana'] = 'Never'
start['Maine'] = '2002-Q1'
start['Maryland'] = '2007-Q1'
start['Massachusetts'] = 'Always'
start['Michigan'] = '2006-Q4'
start['Minnesota'] = '2005-Q3'
start['Mississippi'] = 'Never'
start['Missouri'] = '2007-Q1'
start['Montana'] = '2007-Q1'
start['Nebraska'] = 'Never'
start['Nevada'] = '2006-Q4'
start['New Hampshire'] = 'Never'
start['New Jersey'] = '2005-4'
start['New Mexico'] = 'Never'
start['New York'] = '2005-Q1'
start['North Carolina'] = '2007-Q1'
start['North Dakota'] = 'Never'
start['Ohio'] = '2007-Q1'
start['Oklahoma'] = 'Never'
start['Oregon'] = 'Always'
start['Pennsylvania'] = '2007-Q1'
start['Rhode Island'] = '1999-Q3'
start['South Carolina'] = 'Never'
start['South Dakota'] = 'Never'
start['Tennessee'] = 'Never'
start['Texas'] = 'Never'
start['Utah'] = 'Never'
start['Vermont'] = 'Always'
start['Virginia'] = 'Never'
start['Washington'] = '1991-Q1'
start['West Virginia'] = '2006-Q3'
start['Wisconsin'] = '2005-Q2'
start['Wyoming'] = 'Never'

In [13]:
print(start)

{'Alabama': 'Never', 'Alaska': 'Always', 'Arizona': '2007-Q1', 'Arkansas': '2006-Q4', 'California': 'Always', 'Colorado': '2007-Q1', 'Connecticut': 'Always', 'Delaware': '1999-Q2', 'Florida': '2005-Q2', 'Georgia': 'Never', 'Hawaii': 'Always', 'Idaho': 'Never', 'Illinois': '2004-Q1', 'Indiana': 'Never', 'Iowa': '2007-Q2', 'Kansas': 'Never', 'Kentucky': 'Never', 'Louisiana': 'Never', 'Maine': '2002-Q1', 'Maryland': '2007-Q1', 'Massachusetts': 'Always', 'Michigan': '2006-Q4', 'Minnesota': '2005-Q3', 'Mississippi': 'Never', 'Missouri': '2007-Q1', 'Montana': '2007-Q1', 'Nebraska': 'Never', 'Nevada': '2006-Q4', 'New Hampshire': 'Never', 'New Jersey': '2005-4', 'New Mexico': 'Never', 'New York': '2005-Q1', 'North Carolina': '2007-Q1', 'North Dakota': 'Never', 'Ohio': '2007-Q1', 'Oklahoma': 'Never', 'Oregon': 'Always', 'Pennsylvania': '2007-Q1', 'Rhode Island': '1999-Q3', 'South Carolina': 'Never', 'South Dakota': 'Never', 'Tennessee': 'Never', 'Texas': 'Never', 'Utah': 'Never', 'Vermont': 'Always', 'Virginia': 'Never', 'Washington': '1991-Q1', 'West Virginia': '2006-Q3', 'Wisconsin': '2005-Q2', 'Wyoming': 'Never'}

In [14]:
# map the dictionary to the column of state names
b_ool = 1
data['rollout_date'] = data['state_name'].map(start)

C:\Users\rodri\AppData\Local\Temp/ipykernel_12340/990059774.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['rollout_date'] = data['state_name'].map(start)

In [15]:
data.head()

  state_name state_fips     county_name county_fips rollout_date
0    Alabama      01000  Autauga County       01001        Never
1    Alabama      01000  Baldwin County       01003        Never
2    Alabama      01000  Barbour County       01005        Never
3    Alabama      01000     Bibb County       01007        Never
4    Alabama      01000   Blount County       01009        Never

In [16]:
# drop the states that I will not use
drop_states = ['Alaska', 'Hawaii', 'Massachusetts', 'District of Columbia']
data = data.loc[~data['state_name'].isin(drop_states), ]

In [17]:
data.to_csv('../data/working/all_states_for_policy.csv')

In [18]:
# drop states that were always above the minimum wage
data = data.loc[data['rollout_date'] != 'Always', ]

In [19]:
print(data['rollout_date'].unique())

['Never' '2007-Q1' '2006-Q4' '1999-Q2' '2005-Q2' '2004-Q1' '2007-Q2'
 '2002-Q1' '2005-Q3' '2005-4' '2005-Q1' '1999-Q3' '1991-Q1' '2006-Q3']

In [20]:
data.head()

  state_name state_fips     county_name county_fips rollout_date
0    Alabama      01000  Autauga County       01001        Never
1    Alabama      01000  Baldwin County       01003        Never
2    Alabama      01000  Barbour County       01005        Never
3    Alabama      01000     Bibb County       01007        Never
4    Alabama      01000   Blount County       01009        Never

In [21]:
print(len(data['state_name'].unique()))

43

In [22]:
# drop the states that were treated prior to 2001
drop_early_treated = ['Delaware', 'Rhode Island', 'Washington']
data = data.loc[~data['state_name'].isin(drop_early_treated), ]

In [23]:
print(len(data['state_name'].unique()))

40

In [24]:
# drop states that do not share a border with a never treated or a treated state
drop_northeast = ['Maine', 'New Hampshire', 'New York', 'Pennsylvania', 'New Jersey']
data = data.loc[~data['state_name'].isin(drop_northeast)]

In [25]:
# drop state Arizona
data = data.loc[data['state_name'] != 'Arizona']
# drop state Arkansas
data = data.loc[data['state_name'] != 'Arkansas']

In [26]:
print(len(data['state_name'].unique()))

33

In [27]:
print(data['state_name'].unique())

['Alabama' 'Colorado' 'Florida' 'Georgia' 'Idaho' 'Illinois' 'Indiana'
 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maryland' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Mexico'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Virginia' 'West Virginia'
 'Wisconsin' 'Wyoming']

In [28]:
# drop never treated units
drop_never = ['Alabama', 'Mississippi', 'Kentucky', 'Wyoming']
data = data.loc[~data['state_name'].isin(drop_never)]

In [29]:
print(data['state_name'].unique())

['Colorado' 'Florida' 'Georgia' 'Idaho' 'Illinois' 'Indiana' 'Iowa'
 'Kansas' 'Louisiana' 'Maryland' 'Michigan' 'Minnesota' 'Missouri'
 'Montana' 'Nebraska' 'Nevada' 'New Mexico' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'South Carolina' 'South Dakota'
 'Tennessee' 'Texas' 'Utah' 'Virginia' 'West Virginia' 'Wisconsin']

In [30]:
print(len(data['state_name'].unique()))

29

In [31]:
data.to_csv('../data/working/policy_states.csv')